import { Injectable } from '@nestjs/common';
import { EntityManager } from 'typeorm';
import { APP_CONSTANTS } from '@common/constants/app.constant';
import {
  CredentialEventType,
  CredentialRequestStatus,
  CredentialTemplateStatus,
} from '@common/constants/credential.enum';
import { ExamAttempt } from './entities/exam-attempt.entity';
import { CredentialTemplate } from '@modules/admin/credential/entities/credential-template.entity';
import { CredentialRequest } from '@modules/admin/credential/entities/credential-request.entity';
import { CredentialEvent } from '@modules/admin/credential/entities/credential-event.entity';

export interface CredentialEligibilityResult {
  eligibleByScore: boolean;
  requestCreated: boolean;
  requestId: string | null;
  requestStatus: CredentialRequestStatus | null;
  credentialTemplateId: string | null;
  reason: string | null;
}

@Injectable()
export class CredentialEligibilityService {
  async evaluateAttempt(
    manager: EntityManager,
    attempt: ExamAttempt,
  ): Promise<CredentialEligibilityResult> {
    const totalScore = Number(attempt.totalScore);
    const threshold =
      attempt.passThresholdSnapshot ?? APP_CONSTANTS.CERTIFICATE_PASS_THRESHOLD;

    if (totalScore < threshold) {
      return {
        eligibleByScore: false,
        requestCreated: false,
        requestId: null,
        requestStatus: null,
        credentialTemplateId: null,
        reason: 'score_below_threshold',
      };
    }

    const requestRepository = manager.getRepository(CredentialRequest);
    const existingRequest = await requestRepository.findOne({
      where: { examAttemptId: attempt.id },
      relations: { credentialTemplate: true },
    });

    if (existingRequest) {
      return {
        eligibleByScore: true,
        requestCreated: false,
        requestId: existingRequest.id,
        requestStatus: existingRequest.status,
        credentialTemplateId: existingRequest.credentialTemplateId,
        reason: 'request_already_exists',
      };
    }

    const template = await this.findMatchingTemplate(manager, totalScore);
    if (!template) {
      return {
        eligibleByScore: true,
        requestCreated: false,
        requestId: null,
        requestStatus: null,
        credentialTemplateId: null,
        reason: 'no_matching_published_credential_template',
      };
    }

    const now = new Date();
    const request = requestRepository.create({
      status: CredentialRequestStatus.PENDING,
      userId: attempt.userId,
      credentialTemplateId: template.id,
      examTemplateId: attempt.examTemplateId,
      examAttemptId: attempt.id,
      eligibilitySource: 'exam_result',
      sourceRef: attempt.id,
      eligibilityScore: attempt.totalScore,
      passThresholdSnapshot: threshold,
      requestedAt: now,
      approvedPayload: {
        examAttemptId: attempt.id,
        templateId: attempt.examTemplateId,
        totalScore,
        threshold,
        scoringVersion: attempt.scoringVersion,
      },
      metadata: {
        autoGenerated: true,
        mode: attempt.mode,
        startedAt: attempt.startedAt.toISOString(),
        submittedAt: attempt.submittedAt?.toISOString() ?? null,
      },
    });

    const savedRequest = await requestRepository.save(request);

    const eventRepository = manager.getRepository(CredentialEvent);
    await eventRepository.save(
      eventRepository.create({
        credentialRequestId: savedRequest.id,
        actorId: attempt.userId,
        eventType: CredentialEventType.REQUESTED,
        note: 'Tu dong tao yeu cau cap chung chi tu ket qua thi',
        occurredAt: now,
        payload: {
          trigger: 'exam_attempt_submit',
          examAttemptId: attempt.id,
          totalScore,
          threshold,
          credentialTemplateId: template.id,
        },
      }),
    );

    return {
      eligibleByScore: true,
      requestCreated: true,
      requestId: savedRequest.id,
      requestStatus: savedRequest.status,
      credentialTemplateId: template.id,
      reason: null,
    };
  }

  private async findMatchingTemplate(
    manager: EntityManager,
    totalScore: number,
  ) {
    return manager
      .getRepository(CredentialTemplate)
      .createQueryBuilder('template')
      .where('template.status = :status', {
        status: CredentialTemplateStatus.PUBLISHED,
      })
      .andWhere(
        '(template.passScoreThreshold IS NULL OR template.passScoreThreshold <= :totalScore)',
        { totalScore },
      )
      .orderBy('COALESCE(template.passScoreThreshold, 0)', 'DESC')
      .addOrderBy('template.publishedAt', 'DESC', 'NULLS LAST')
      .addOrderBy('template.createdAt', 'DESC')
      .getOne();
  }
}
